# Generated by Django 5.1.4 on 2024-12-11 23:50

import api.models.blog
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(default='posts/default.jpg', upload_to=api.models.blog.upload_to)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=200, unique_for_date='published')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
